const API = {
  login: "/api/auth/login",
  logout: "/api/auth/logout",
  user: "/api/auth/user",
  skills: "/api/skills",
  about: "/api/about",
  file: "/api/file",
  sponsor: "/api/sponsor",
  committee: "/api/committee",
  events: "/api/events",
  upcomingEvents: "/api/events/upcoming",
  notices: "/api/notices",
  blogs: "/api/blogs",
  contact: "/api/contact",
  testimonials: "/api/testimonials",
  recentNotices: "/api/notices/recent",
  tags: "/api/tags",
  blogTags: "/api/blogs/tags",
  blogAuthors: "/api/blogs/authors",
  blogByTag: "/api/blogs/tags",
  blogByAuthor: "/api/blogs/authors",
  gallery: "/api/gallery",
  dashboard: "/api/dashboard",
  trainingAndWorkshops: "/api/training-and-workshops",
} as const;

export default API;
