import discord from "@/assets/icons/discord.svg";
export const ICONS = {
  discord,
  typescript: "https://www.svgrepo.com/show/349540/typescript.svg",
  flutter: "https://www.svgrepo.com/show/353751/flutter.svg",
  react: "https://www.svgrepo.com/show/452092/react.svg",
  java: "https://www.svgrepo.com/show/452234/java.svg",
  kali: "https://www.svgrepo.com/show/330767/kalilinux.svg",
  vscode: "https://www.svgrepo.com/show/374169/vscode2.svg",
  gitlab: "https://www.svgrepo.com/show/448226/gitlab.svg",
  figma: "https://www.svgrepo.com/show/452202/figma.svg",
  github: "https://www.svgrepo.com/show/452211/github.svg",
  facebook: "https://www.svgrepo.com/show/448224/facebook.svg",
  twitter: "https://www.svgrepo.com/show/176772/twitter-social-media.svg",
  linkedin: "https://www.svgrepo.com/show/452047/linkedin-1.svg",
  instagram: "https://www.svgrepo.com/show/452229/instagram-1.svg",
  external: "https://www.svgrepo.com/show/458672/external-1.svg",
  email: "https://www.svgrepo.com/show/353812/google-gmail.svg",
  tel: "https://www.svgrepo.com/show/518546/phone-alt2.svg",
  youtube: "https://www.svgrepo.com/show/475700/youtube-color.svg",
  ubuntu: "https://www.svgrepo.com/show/452122/ubuntu.svg",
  linux: "https://www.svgrepo.com/show/444160/os-linux.svg",
  python: "https://www.svgrepo.com/show/452091/python.svg",
  cpp: "https://www.svgrepo.com/show/373528/cpp3.svg",
  nextjs: "https://www.svgrepo.com/show/368858/nextjs.svg",
  arch: "https://www.svgrepo.com/show/349296/arch-linux.svg",
};
